dist: xenial
language: python
python: 3.7

install:
  -

services:
  - docker

env:
  - COMPOSE_FILE=docker-compose.yml

script:
  - docker-compose build
  - docker-compose run service python -m unittest
